# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_templates/input_system.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_input_system(object):
    def setupUi(self, input_system):
        input_system.setObjectName("input_system")
        input_system.resize(408, 303)

        self.retranslateUi(input_system)
        QtCore.QMetaObject.connectSlotsByName(input_system)

    def retranslateUi(self, input_system):
        _translate = QtCore.QCoreApplication.translate
        input_system.setWindowTitle(_translate("input_system", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    input_system = QtWidgets.QDialog()
    ui = Ui_input_system()
    ui.setupUi(input_system)
    input_system.show()
    sys.exit(app.exec_())
